version: "3"

services:
  node:
    build:
      context: .docker/node
    ports:
      - 3000:3000
    working_dir: /opt/app
    tty: true
    volumes:
      - ./logs:/root/.npm/_logs
      - ./workspace:/opt/app
